name: CI

on:
  - pull_request

jobs:
  check-dict-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if word is in dictionary
        run: hack/check-dict-api.sh
